<?php
/**
 * DealerSummary
 *
 * PHP version 5
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v2-listings service v2.0-listings
 *
 * AutoTrader REST service
 *
 * OpenAPI spec version: v2-listings
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AutoTrader\Client\Test\Model;

use \ArrayAccess;
use \AutoTrader\Client\Test\ObjectSerializer;

/**
 * DealerSummary Class Doc Comment
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DealerSummary implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DealerSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'dealer_id' => 'int',
        'billing_id' => 'string',
        'dealer_name' => 'string',
        'dealer_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'dealer_id' => 'int32',
        'billing_id' => null,
        'dealer_name' => null,
        'dealer_status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dealer_id' => 'dealerId',
        'billing_id' => 'billingId',
        'dealer_name' => 'dealerName',
        'dealer_status' => 'dealerStatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dealer_id' => 'setDealerId',
        'billing_id' => 'setBillingId',
        'dealer_name' => 'setDealerName',
        'dealer_status' => 'setDealerStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dealer_id' => 'getDealerId',
        'billing_id' => 'getBillingId',
        'dealer_name' => 'getDealerName',
        'dealer_status' => 'getDealerStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const DEALER_STATUS_ACTIVE = 'Active';
    const DEALER_STATUS_IN_ACTIVE = 'InActive';



    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDealerStatusAllowableValues()
    {
        return [
            self::DEALER_STATUS_ACTIVE,
            self::DEALER_STATUS_IN_ACTIVE,
        ];
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dealer_id'] = isset($data['dealer_id']) ? $data['dealer_id'] : null;
        $this->container['billing_id'] = isset($data['billing_id']) ? $data['billing_id'] : null;
        $this->container['dealer_name'] = isset($data['dealer_name']) ? $data['dealer_name'] : null;
        $this->container['dealer_status'] = isset($data['dealer_status']) ? $data['dealer_status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['dealer_id'] === null) {
            $invalidProperties[] = "'dealer_id' can't be null";
        }
        if ($this->container['dealer_status'] === null) {
            $invalidProperties[] = "'dealer_status' can't be null";
        }
        $allowedValues = $this->getDealerStatusAllowableValues();
        if (!is_null($this->container['dealer_status']) && !in_array($this->container['dealer_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'dealer_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dealer_id
     *
     * @return int
     */
    public function getDealerId()
    {
        return $this->container['dealer_id'];
    }

    /**
     * Sets dealer_id
     *
     * @param int $dealer_id dealer_id
     *
     * @return $this
     */
    public function setDealerId($dealer_id)
    {
        $this->container['dealer_id'] = $dealer_id;

        return $this;
    }

    /**
     * Gets billing_id
     *
     * @return string
     */
    public function getBillingId()
    {
        return $this->container['billing_id'];
    }

    /**
     * Sets billing_id
     *
     * @param string $billing_id billing_id
     *
     * @return $this
     */
    public function setBillingId($billing_id)
    {
        $this->container['billing_id'] = $billing_id;

        return $this;
    }

    /**
     * Gets dealer_name
     *
     * @return string
     */
    public function getDealerName()
    {
        return $this->container['dealer_name'];
    }

    /**
     * Sets dealer_name
     *
     * @param string $dealer_name dealer_name
     *
     * @return $this
     */
    public function setDealerName($dealer_name)
    {
        $this->container['dealer_name'] = $dealer_name;

        return $this;
    }

    /**
     * Gets dealer_status
     *
     * @return string
     */
    public function getDealerStatus()
    {
        return $this->container['dealer_status'];
    }

    /**
     * Sets dealer_status
     *
     * @param string $dealer_status dealer_status
     *
     * @return $this
     */
    public function setDealerStatus($dealer_status)
    {
        $allowedValues = $this->getDealerStatusAllowableValues();
        if (!in_array($dealer_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'dealer_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['dealer_status'] = $dealer_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


