<?php
/**
 * MakeModelRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v2-listings service v2.0-listings
 *
 * AutoTrader REST service
 *
 * OpenAPI spec version: v2-listings
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AutoTrader\Client\Test\Model;

use \ArrayAccess;
use \AutoTrader\Client\Test\ObjectSerializer;

/**
 * MakeModelRequest Class Doc Comment
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MakeModelRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MakeModelRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'category' => 'string',
        'make' => 'string',
        'model' => 'string',
        'model_body_shape' => 'string',
        'transmission_type' => 'string',
        'drive_type' => 'string',
        'fuel_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'category' => null,
        'make' => null,
        'model' => null,
        'model_body_shape' => null,
        'transmission_type' => null,
        'drive_type' => null,
        'fuel_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'category' => 'category',
        'make' => 'make',
        'model' => 'model',
        'model_body_shape' => 'modelBodyShape',
        'transmission_type' => 'transmissionType',
        'drive_type' => 'driveType',
        'fuel_type' => 'fuelType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'category' => 'setCategory',
        'make' => 'setMake',
        'model' => 'setModel',
        'model_body_shape' => 'setModelBodyShape',
        'transmission_type' => 'setTransmissionType',
        'drive_type' => 'setDriveType',
        'fuel_type' => 'setFuelType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'category' => 'getCategory',
        'make' => 'getMake',
        'model' => 'getModel',
        'model_body_shape' => 'getModelBodyShape',
        'transmission_type' => 'getTransmissionType',
        'drive_type' => 'getDriveType',
        'fuel_type' => 'getFuelType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CATEGORY_CARS = 'Cars';
    const CATEGORY_BIKES = 'Bikes';
    const CATEGORY_BOATS = 'Boats';
    const CATEGORY_CARAVANS = 'Caravans';
    const CATEGORY_TRACTORS = 'Tractors';
    const CATEGORY_TRAILERS = 'Trailers';
    const CATEGORY_ATTACHMENTS = 'Attachments';
    const CATEGORY_LOADERS = 'Loaders';
    const CATEGORY_EXCAVATORS = 'Excavators';
    const CATEGORY_TRUCKS = 'Trucks';
    const CATEGORY_GRADERS = 'Graders';
    const CATEGORY_ROLLERS = 'Rollers';
    const CATEGORY_DOZERS = 'Dozers';
    const CATEGORY_CRANES = 'Cranes';
    const CATEGORY_BUSES = 'Buses';
    const CATEGORY_BAKKIES = 'Bakkies';
    const CATEGORY_VANS = 'Vans';
    const CATEGORY_FORKLIFTS = 'Forklifts';
    const TRANSMISSION_TYPE_MANUAL = 'Manual';
    const TRANSMISSION_TYPE_AUTOMATIC = 'Automatic';
    const TRANSMISSION_TYPE_SEMI_AUTOMATIC = 'SemiAutomatic';
    const DRIVE_TYPE__4X2 = '_4x2';
    const DRIVE_TYPE__4X4 = '_4x4';
    const DRIVE_TYPE_ALL_WHEEL_DRIVE = 'AllWheelDrive';
    const DRIVE_TYPE_FRONT_WHEEL_DRIVE = 'FrontWheelDrive';
    const DRIVE_TYPE_REAR_WHEEL_DRIVE = 'RearWheelDrive';
    const DRIVE_TYPE_FOUR_WHEEL_DRIVE = 'FourWheelDrive';
    const FUEL_TYPE_PETROL = 'Petrol';
    const FUEL_TYPE_DIESEL = 'Diesel';
    const FUEL_TYPE_BIO_DIESEL = 'BioDiesel';
    const FUEL_TYPE_HYBRID = 'Hybrid';
    const FUEL_TYPE_ELECTRIC = 'Electric';
    const FUEL_TYPE_BI_FUEL = 'BiFuel';
    const FUEL_TYPE_LPG = 'LPG';
    const FUEL_TYPE_LNG = 'LNG';
    const FUEL_TYPE_CNG = 'CNG';
    const FUEL_TYPE_DUAL_FUEL = 'DualFuel';
    const FUEL_TYPE_HYDROGEN = 'Hydrogen';
    const FUEL_TYPE_OTHER = 'Other';



    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCategoryAllowableValues()
    {
        return [
            self::CATEGORY_CARS,
            self::CATEGORY_BIKES,
            self::CATEGORY_BOATS,
            self::CATEGORY_CARAVANS,
            self::CATEGORY_TRACTORS,
            self::CATEGORY_TRAILERS,
            self::CATEGORY_ATTACHMENTS,
            self::CATEGORY_LOADERS,
            self::CATEGORY_EXCAVATORS,
            self::CATEGORY_TRUCKS,
            self::CATEGORY_GRADERS,
            self::CATEGORY_ROLLERS,
            self::CATEGORY_DOZERS,
            self::CATEGORY_CRANES,
            self::CATEGORY_BUSES,
            self::CATEGORY_BAKKIES,
            self::CATEGORY_VANS,
            self::CATEGORY_FORKLIFTS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTransmissionTypeAllowableValues()
    {
        return [
            self::TRANSMISSION_TYPE_MANUAL,
            self::TRANSMISSION_TYPE_AUTOMATIC,
            self::TRANSMISSION_TYPE_SEMI_AUTOMATIC,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDriveTypeAllowableValues()
    {
        return [
            self::DRIVE_TYPE__4X2,
            self::DRIVE_TYPE__4X4,
            self::DRIVE_TYPE_ALL_WHEEL_DRIVE,
            self::DRIVE_TYPE_FRONT_WHEEL_DRIVE,
            self::DRIVE_TYPE_REAR_WHEEL_DRIVE,
            self::DRIVE_TYPE_FOUR_WHEEL_DRIVE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFuelTypeAllowableValues()
    {
        return [
            self::FUEL_TYPE_PETROL,
            self::FUEL_TYPE_DIESEL,
            self::FUEL_TYPE_BIO_DIESEL,
            self::FUEL_TYPE_HYBRID,
            self::FUEL_TYPE_ELECTRIC,
            self::FUEL_TYPE_BI_FUEL,
            self::FUEL_TYPE_LPG,
            self::FUEL_TYPE_LNG,
            self::FUEL_TYPE_CNG,
            self::FUEL_TYPE_DUAL_FUEL,
            self::FUEL_TYPE_HYDROGEN,
            self::FUEL_TYPE_OTHER,
        ];
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['make'] = isset($data['make']) ? $data['make'] : null;
        $this->container['model'] = isset($data['model']) ? $data['model'] : null;
        $this->container['model_body_shape'] = isset($data['model_body_shape']) ? $data['model_body_shape'] : null;
        $this->container['transmission_type'] = isset($data['transmission_type']) ? $data['transmission_type'] : null;
        $this->container['drive_type'] = isset($data['drive_type']) ? $data['drive_type'] : null;
        $this->container['fuel_type'] = isset($data['fuel_type']) ? $data['fuel_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['category'] === null) {
            $invalidProperties[] = "'category' can't be null";
        }
        $allowedValues = $this->getCategoryAllowableValues();
        if (!is_null($this->container['category']) && !in_array($this->container['category'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'category', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTransmissionTypeAllowableValues();
        if (!is_null($this->container['transmission_type']) && !in_array($this->container['transmission_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'transmission_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDriveTypeAllowableValues();
        if (!is_null($this->container['drive_type']) && !in_array($this->container['drive_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'drive_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFuelTypeAllowableValues();
        if (!is_null($this->container['fuel_type']) && !in_array($this->container['fuel_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'fuel_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $allowedValues = $this->getCategoryAllowableValues();
        if (!in_array($category, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'category', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets make
     *
     * @return string
     */
    public function getMake()
    {
        return $this->container['make'];
    }

    /**
     * Sets make
     *
     * @param string $make make
     *
     * @return $this
     */
    public function setMake($make)
    {
        $this->container['make'] = $make;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string $model model
     *
     * @return $this
     */
    public function setModel($model)
    {
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets model_body_shape
     *
     * @return string
     */
    public function getModelBodyShape()
    {
        return $this->container['model_body_shape'];
    }

    /**
     * Sets model_body_shape
     *
     * @param string $model_body_shape model_body_shape
     *
     * @return $this
     */
    public function setModelBodyShape($model_body_shape)
    {
        $this->container['model_body_shape'] = $model_body_shape;

        return $this;
    }

    /**
     * Gets transmission_type
     *
     * @return string
     */
    public function getTransmissionType()
    {
        return $this->container['transmission_type'];
    }

    /**
     * Sets transmission_type
     *
     * @param string $transmission_type transmission_type
     *
     * @return $this
     */
    public function setTransmissionType($transmission_type)
    {
        $allowedValues = $this->getTransmissionTypeAllowableValues();
        if (!is_null($transmission_type) && !in_array($transmission_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'transmission_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['transmission_type'] = $transmission_type;

        return $this;
    }

    /**
     * Gets drive_type
     *
     * @return string
     */
    public function getDriveType()
    {
        return $this->container['drive_type'];
    }

    /**
     * Sets drive_type
     *
     * @param string $drive_type drive_type
     *
     * @return $this
     */
    public function setDriveType($drive_type)
    {
        $allowedValues = $this->getDriveTypeAllowableValues();
        if (!is_null($drive_type) && !in_array($drive_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'drive_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['drive_type'] = $drive_type;

        return $this;
    }

    /**
     * Gets fuel_type
     *
     * @return string
     */
    public function getFuelType()
    {
        return $this->container['fuel_type'];
    }

    /**
     * Sets fuel_type
     *
     * @param string $fuel_type fuel_type
     *
     * @return $this
     */
    public function setFuelType($fuel_type)
    {
        $allowedValues = $this->getFuelTypeAllowableValues();
        if (!is_null($fuel_type) && !in_array($fuel_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'fuel_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fuel_type'] = $fuel_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


