<?php
/**
 * DealerSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v2-listings service v2.0-listings
 *
 * AutoTrader REST service
 *
 * OpenAPI spec version: v2-listings
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AutoTrader\Client\Test;

/**
 * DealerSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description DealerSummary
 * @package     AutoTrader\Client\Test
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DealerSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DealerSummary"
     */
    public function testDealerSummary()
    {
    }

    /**
     * Test attribute "dealer_id"
     */
    public function testPropertyDealerId()
    {
    }

    /**
     * Test attribute "billing_id"
     */
    public function testPropertyBillingId()
    {
    }

    /**
     * Test attribute "dealer_name"
     */
    public function testPropertyDealerName()
    {
    }

    /**
     * Test attribute "dealer_status"
     */
    public function testPropertyDealerStatus()
    {
    }
}
