<?php
/**
 * ListingSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v2-listings service v2.0-listings
 *
 * AutoTrader REST service
 *
 * OpenAPI spec version: v2-listings
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AutoTrader\Client\Test;

/**
 * ListingSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description ListingSummary
 * @package     AutoTrader\Client\Test
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListingSummary"
     */
    public function testListingSummary()
    {
    }

    /**
     * Test attribute "listing_id"
     */
    public function testPropertyListingId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "vehicle_specification_id"
     */
    public function testPropertyVehicleSpecificationId()
    {
    }

    /**
     * Test attribute "vehicle_category"
     */
    public function testPropertyVehicleCategory()
    {
    }

    /**
     * Test attribute "vehicle_sub_category"
     */
    public function testPropertyVehicleSubCategory()
    {
    }

    /**
     * Test attribute "update_date"
     */
    public function testPropertyUpdateDate()
    {
    }

    /**
     * Test attribute "stock_number"
     */
    public function testPropertyStockNumber()
    {
    }

    /**
     * Test attribute "dealer_id"
     */
    public function testPropertyDealerId()
    {
    }
}
