<?php
/**
 * ListingModelReadOnlyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v2-listings service v2.0-listings
 *
 * AutoTrader REST service
 *
 * OpenAPI spec version: v2-listings
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AutoTrader\Client\Test;

/**
 * ListingModelReadOnlyTest Class Doc Comment
 *
 * @category    Class
 * @description ListingModelReadOnly
 * @package     AutoTrader\Client\Test
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingModelReadOnlyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListingModelReadOnly"
     */
    public function testListingModelReadOnly()
    {
    }

    /**
     * Test attribute "dealer_id"
     */
    public function testPropertyDealerId()
    {
    }

    /**
     * Test attribute "new_used"
     */
    public function testPropertyNewUsed()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "sub_category"
     */
    public function testPropertySubCategory()
    {
    }

    /**
     * Test attribute "body_type"
     */
    public function testPropertyBodyType()
    {
    }

    /**
     * Test attribute "vin"
     */
    public function testPropertyVin()
    {
    }

    /**
     * Test attribute "stock_number"
     */
    public function testPropertyStockNumber()
    {
    }

    /**
     * Test attribute "registration_number"
     */
    public function testPropertyRegistrationNumber()
    {
    }

    /**
     * Test attribute "registration_year"
     */
    public function testPropertyRegistrationYear()
    {
    }

    /**
     * Test attribute "mileage"
     */
    public function testPropertyMileage()
    {
    }

    /**
     * Test attribute "previous_owners"
     */
    public function testPropertyPreviousOwners()
    {
    }

    /**
     * Test attribute "service_history"
     */
    public function testPropertyServiceHistory()
    {
    }

    /**
     * Test attribute "warranty_remaining_in_months"
     */
    public function testPropertyWarrantyRemainingInMonths()
    {
    }

    /**
     * Test attribute "colour"
     */
    public function testPropertyColour()
    {
    }

    /**
     * Test attribute "manufacturer_colour"
     */
    public function testPropertyManufacturerColour()
    {
    }

    /**
     * Test attribute "engine_capacity"
     */
    public function testPropertyEngineCapacity()
    {
    }

    /**
     * Test attribute "engine_capacity_unit"
     */
    public function testPropertyEngineCapacityUnit()
    {
    }

    /**
     * Test attribute "engine_power"
     */
    public function testPropertyEnginePower()
    {
    }

    /**
     * Test attribute "engine_power_unit"
     */
    public function testPropertyEnginePowerUnit()
    {
    }

    /**
     * Test attribute "number_of_berths"
     */
    public function testPropertyNumberOfBerths()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "max_payload"
     */
    public function testPropertyMaxPayload()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "lifting_capacity"
     */
    public function testPropertyLiftingCapacity()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "axle_configuration"
     */
    public function testPropertyAxleConfiguration()
    {
    }

    /**
     * Test attribute "axles"
     */
    public function testPropertyAxles()
    {
    }

    /**
     * Test attribute "fuel_type"
     */
    public function testPropertyFuelType()
    {
    }

    /**
     * Test attribute "transmission"
     */
    public function testPropertyTransmission()
    {
    }

    /**
     * Test attribute "transmission_drive"
     */
    public function testPropertyTransmissionDrive()
    {
    }

    /**
     * Test attribute "hours_in_operation"
     */
    public function testPropertyHoursInOperation()
    {
    }

    /**
     * Test attribute "maximum_reach"
     */
    public function testPropertyMaximumReach()
    {
    }

    /**
     * Test attribute "specification_features"
     */
    public function testPropertySpecificationFeatures()
    {
    }

    /**
     * Test attribute "features"
     */
    public function testPropertyFeatures()
    {
    }

    /**
     * Test attribute "sellers_comments"
     */
    public function testPropertySellersComments()
    {
    }

    /**
     * Test attribute "trade_in_price"
     */
    public function testPropertyTradeInPrice()
    {
    }

    /**
     * Test attribute "reconditioning_costs"
     */
    public function testPropertyReconditioningCosts()
    {
    }

    /**
     * Test attribute "list_price"
     */
    public function testPropertyListPrice()
    {
    }

    /**
     * Test attribute "poa"
     */
    public function testPropertyPoa()
    {
    }

    /**
     * Test attribute "is_featured_listing"
     */
    public function testPropertyIsFeaturedListing()
    {
    }

    /**
     * Test attribute "image_urls"
     */
    public function testPropertyImageUrls()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "rebuild"
     */
    public function testPropertyRebuild()
    {
    }

    /**
     * Test attribute "make"
     */
    public function testPropertyMake()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "variant"
     */
    public function testPropertyVariant()
    {
    }

    /**
     * Test attribute "transmission_type"
     */
    public function testPropertyTransmissionType()
    {
    }

    /**
     * Test attribute "drive_type"
     */
    public function testPropertyDriveType()
    {
    }

    /**
     * Test attribute "number_of_doors"
     */
    public function testPropertyNumberOfDoors()
    {
    }

    /**
     * Test attribute "introduction_date"
     */
    public function testPropertyIntroductionDate()
    {
    }

    /**
     * Test attribute "discontinued_date"
     */
    public function testPropertyDiscontinuedDate()
    {
    }
}
