<?php
/**
 * SpecificationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AutoTrader\Client\Test
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v2-listings service v2.0-listings
 *
 * AutoTrader REST service
 *
 * OpenAPI spec version: v2-listings
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AutoTrader\Client\Test;

/**
 * SpecificationTest Class Doc Comment
 *
 * @category    Class
 * @description Specification
 * @package     AutoTrader\Client\Test
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpecificationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Specification"
     */
    public function testSpecification()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "vehicle_make"
     */
    public function testPropertyVehicleMake()
    {
    }

    /**
     * Test attribute "vehicle_model"
     */
    public function testPropertyVehicleModel()
    {
    }

    /**
     * Test attribute "vehicle_long_variant"
     */
    public function testPropertyVehicleLongVariant()
    {
    }

    /**
     * Test attribute "model_body_shape"
     */
    public function testPropertyModelBodyShape()
    {
    }

    /**
     * Test attribute "transmission_type"
     */
    public function testPropertyTransmissionType()
    {
    }

    /**
     * Test attribute "drive_type"
     */
    public function testPropertyDriveType()
    {
    }

    /**
     * Test attribute "fuel_type"
     */
    public function testPropertyFuelType()
    {
    }

    /**
     * Test attribute "engine_capacity"
     */
    public function testPropertyEngineCapacity()
    {
    }

    /**
     * Test attribute "number_of_doors"
     */
    public function testPropertyNumberOfDoors()
    {
    }

    /**
     * Test attribute "introduction_date"
     */
    public function testPropertyIntroductionDate()
    {
    }

    /**
     * Test attribute "discontinued_date"
     */
    public function testPropertyDiscontinuedDate()
    {
    }

    /**
     * Test attribute "tumm_code"
     */
    public function testPropertyTummCode()
    {
    }
}
